env: local
http_port: 8080
db: "./storage/marketplace.db"
JWT_ACCESS_SECRET: "1234567890abcdef1234567890abcdef"
JWT_REFRESH_SECRET: "1234567890abcdef1234567890abcdef"
JWT_EXP_ACCESS_TOKEN: 15 # minutes
JWT_EXP_REFRESH_TOKEN: 24 # hours
username:
    min_length: 3
    max_length: 20
    allowed_characters: "A-Za-z0-9_-"
    case_insensitive: true
password:
    min_length: 8
    max_length: 64
    require_upper: true
    require_lower: true
    require_digit: true
ad:
    min_length_title: 3
    max_length_title: 100
    min_length_description: 10
    max_length_description: 1000
    img_type: 
        - jpg
        - jpeg
        - png
        - webm
    price_min: 0.01